/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AppRealizadoRouteImport } from './routes/_app.realizado'
import { Route as AppReajustesRouteImport } from './routes/_app.reajustes'
import { Route as AppRdoRouteImport } from './routes/_app.rdo'
import { Route as AppPropostasRouteImport } from './routes/_app.propostas'
import { Route as AppPortaisRouteImport } from './routes/_app.portais'
import { Route as AppPoderesRouteImport } from './routes/_app.poderes'
import { Route as AppParametrosFinanceirosRouteImport } from './routes/_app.parametros-financeiros'
import { Route as AppOportunidadesRouteImport } from './routes/_app.oportunidades'
import { Route as AppObrasRouteImport } from './routes/_app.obras'
import { Route as AppNotasFiscaisRouteImport } from './routes/_app.notas-fiscais'
import { Route as AppMedicoesRouteImport } from './routes/_app.medicoes'
import { Route as AppMaoDeObraRouteImport } from './routes/_app.mao-de-obra'
import { Route as AppInsumosRouteImport } from './routes/_app.insumos'
import { Route as AppIndicesRouteImport } from './routes/_app.indices'
import { Route as AppFinanceiroRouteImport } from './routes/_app.financeiro'
import { Route as AppEstoqueRouteImport } from './routes/_app.estoque'
import { Route as AppEquipeRouteImport } from './routes/_app.equipe'
import { Route as AppEquipamentosRouteImport } from './routes/_app.equipamentos'
import { Route as AppEditaisRouteImport } from './routes/_app.editais'
import { Route as AppDossiesRouteImport } from './routes/_app.dossies'
import { Route as AppCronogramasRouteImport } from './routes/_app.cronogramas'
import { Route as AppContratosRouteImport } from './routes/_app.contratos'
import { Route as AppComposicoesRouteImport } from './routes/_app.composicoes'
import { Route as AppComplianceRouteImport } from './routes/_app.compliance'
import { Route as AppComparativoComposicaoRouteImport } from './routes/_app.comparativo-composicao'
import { Route as AppCentrosCustoRouteImport } from './routes/_app.centros-custo'
import { Route as AppBibliotecaRouteImport } from './routes/_app.biblioteca'
import { Route as AppBackupRouteImport } from './routes/_app.backup'
import { Route as AppAssinaturasRouteImport } from './routes/_app.assinaturas'
import { Route as AppAditivosRouteImport } from './routes/_app.aditivos'
import { Route as ApiPublicZapsignWebhookRouteImport } from './routes/api.public.zapsign-webhook'
import { Route as ApiPublicZapsignRemindersRouteImport } from './routes/api.public.zapsign-reminders'
import { Route as AppPropostasIdRouteImport } from './routes/_app.propostas.$id'
import { Route as AppInsumosImportarRouteImport } from './routes/_app.insumos.importar'
import { Route as AppConfiguracoesZapsignRouteImport } from './routes/_app.configuracoes.zapsign'
import { Route as AppAssinaturasRelatorioRouteImport } from './routes/_app.assinaturas.relatorio'
import { Route as AppConfiguracoesZapsignTestesRouteImport } from './routes/_app.configuracoes.zapsign.testes'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRealizadoRoute = AppRealizadoRouteImport.update({
  id: '/realizado',
  path: '/realizado',
  getParentRoute: () => AppRoute,
} as any)
const AppReajustesRoute = AppReajustesRouteImport.update({
  id: '/reajustes',
  path: '/reajustes',
  getParentRoute: () => AppRoute,
} as any)
const AppRdoRoute = AppRdoRouteImport.update({
  id: '/rdo',
  path: '/rdo',
  getParentRoute: () => AppRoute,
} as any)
const AppPropostasRoute = AppPropostasRouteImport.update({
  id: '/propostas',
  path: '/propostas',
  getParentRoute: () => AppRoute,
} as any)
const AppPortaisRoute = AppPortaisRouteImport.update({
  id: '/portais',
  path: '/portais',
  getParentRoute: () => AppRoute,
} as any)
const AppPoderesRoute = AppPoderesRouteImport.update({
  id: '/poderes',
  path: '/poderes',
  getParentRoute: () => AppRoute,
} as any)
const AppParametrosFinanceirosRoute =
  AppParametrosFinanceirosRouteImport.update({
    id: '/parametros-financeiros',
    path: '/parametros-financeiros',
    getParentRoute: () => AppRoute,
  } as any)
const AppOportunidadesRoute = AppOportunidadesRouteImport.update({
  id: '/oportunidades',
  path: '/oportunidades',
  getParentRoute: () => AppRoute,
} as any)
const AppObrasRoute = AppObrasRouteImport.update({
  id: '/obras',
  path: '/obras',
  getParentRoute: () => AppRoute,
} as any)
const AppNotasFiscaisRoute = AppNotasFiscaisRouteImport.update({
  id: '/notas-fiscais',
  path: '/notas-fiscais',
  getParentRoute: () => AppRoute,
} as any)
const AppMedicoesRoute = AppMedicoesRouteImport.update({
  id: '/medicoes',
  path: '/medicoes',
  getParentRoute: () => AppRoute,
} as any)
const AppMaoDeObraRoute = AppMaoDeObraRouteImport.update({
  id: '/mao-de-obra',
  path: '/mao-de-obra',
  getParentRoute: () => AppRoute,
} as any)
const AppInsumosRoute = AppInsumosRouteImport.update({
  id: '/insumos',
  path: '/insumos',
  getParentRoute: () => AppRoute,
} as any)
const AppIndicesRoute = AppIndicesRouteImport.update({
  id: '/indices',
  path: '/indices',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppEstoqueRoute = AppEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipeRoute = AppEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipamentosRoute = AppEquipamentosRouteImport.update({
  id: '/equipamentos',
  path: '/equipamentos',
  getParentRoute: () => AppRoute,
} as any)
const AppEditaisRoute = AppEditaisRouteImport.update({
  id: '/editais',
  path: '/editais',
  getParentRoute: () => AppRoute,
} as any)
const AppDossiesRoute = AppDossiesRouteImport.update({
  id: '/dossies',
  path: '/dossies',
  getParentRoute: () => AppRoute,
} as any)
const AppCronogramasRoute = AppCronogramasRouteImport.update({
  id: '/cronogramas',
  path: '/cronogramas',
  getParentRoute: () => AppRoute,
} as any)
const AppContratosRoute = AppContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => AppRoute,
} as any)
const AppComposicoesRoute = AppComposicoesRouteImport.update({
  id: '/composicoes',
  path: '/composicoes',
  getParentRoute: () => AppRoute,
} as any)
const AppComplianceRoute = AppComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AppRoute,
} as any)
const AppComparativoComposicaoRoute =
  AppComparativoComposicaoRouteImport.update({
    id: '/comparativo-composicao',
    path: '/comparativo-composicao',
    getParentRoute: () => AppRoute,
  } as any)
const AppCentrosCustoRoute = AppCentrosCustoRouteImport.update({
  id: '/centros-custo',
  path: '/centros-custo',
  getParentRoute: () => AppRoute,
} as any)
const AppBibliotecaRoute = AppBibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => AppRoute,
} as any)
const AppBackupRoute = AppBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => AppRoute,
} as any)
const AppAssinaturasRoute = AppAssinaturasRouteImport.update({
  id: '/assinaturas',
  path: '/assinaturas',
  getParentRoute: () => AppRoute,
} as any)
const AppAditivosRoute = AppAditivosRouteImport.update({
  id: '/aditivos',
  path: '/aditivos',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicZapsignWebhookRoute = ApiPublicZapsignWebhookRouteImport.update({
  id: '/api/public/zapsign-webhook',
  path: '/api/public/zapsign-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicZapsignRemindersRoute =
  ApiPublicZapsignRemindersRouteImport.update({
    id: '/api/public/zapsign-reminders',
    path: '/api/public/zapsign-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppPropostasIdRoute = AppPropostasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPropostasRoute,
} as any)
const AppInsumosImportarRoute = AppInsumosImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => AppInsumosRoute,
} as any)
const AppConfiguracoesZapsignRoute = AppConfiguracoesZapsignRouteImport.update({
  id: '/configuracoes/zapsign',
  path: '/configuracoes/zapsign',
  getParentRoute: () => AppRoute,
} as any)
const AppAssinaturasRelatorioRoute = AppAssinaturasRelatorioRouteImport.update({
  id: '/relatorio',
  path: '/relatorio',
  getParentRoute: () => AppAssinaturasRoute,
} as any)
const AppConfiguracoesZapsignTestesRoute =
  AppConfiguracoesZapsignTestesRouteImport.update({
    id: '/testes',
    path: '/testes',
    getParentRoute: () => AppConfiguracoesZapsignRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/aditivos': typeof AppAditivosRoute
  '/assinaturas': typeof AppAssinaturasRouteWithChildren
  '/backup': typeof AppBackupRoute
  '/biblioteca': typeof AppBibliotecaRoute
  '/centros-custo': typeof AppCentrosCustoRoute
  '/comparativo-composicao': typeof AppComparativoComposicaoRoute
  '/compliance': typeof AppComplianceRoute
  '/composicoes': typeof AppComposicoesRoute
  '/contratos': typeof AppContratosRoute
  '/cronogramas': typeof AppCronogramasRoute
  '/dossies': typeof AppDossiesRoute
  '/editais': typeof AppEditaisRoute
  '/equipamentos': typeof AppEquipamentosRoute
  '/equipe': typeof AppEquipeRoute
  '/estoque': typeof AppEstoqueRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/indices': typeof AppIndicesRoute
  '/insumos': typeof AppInsumosRouteWithChildren
  '/mao-de-obra': typeof AppMaoDeObraRoute
  '/medicoes': typeof AppMedicoesRoute
  '/notas-fiscais': typeof AppNotasFiscaisRoute
  '/obras': typeof AppObrasRoute
  '/oportunidades': typeof AppOportunidadesRoute
  '/parametros-financeiros': typeof AppParametrosFinanceirosRoute
  '/poderes': typeof AppPoderesRoute
  '/portais': typeof AppPortaisRoute
  '/propostas': typeof AppPropostasRouteWithChildren
  '/rdo': typeof AppRdoRoute
  '/reajustes': typeof AppReajustesRoute
  '/realizado': typeof AppRealizadoRoute
  '/invite/$token': typeof InviteTokenRoute
  '/assinaturas/relatorio': typeof AppAssinaturasRelatorioRoute
  '/configuracoes/zapsign': typeof AppConfiguracoesZapsignRouteWithChildren
  '/insumos/importar': typeof AppInsumosImportarRoute
  '/propostas/$id': typeof AppPropostasIdRoute
  '/api/public/zapsign-reminders': typeof ApiPublicZapsignRemindersRoute
  '/api/public/zapsign-webhook': typeof ApiPublicZapsignWebhookRoute
  '/configuracoes/zapsign/testes': typeof AppConfiguracoesZapsignTestesRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/aditivos': typeof AppAditivosRoute
  '/assinaturas': typeof AppAssinaturasRouteWithChildren
  '/backup': typeof AppBackupRoute
  '/biblioteca': typeof AppBibliotecaRoute
  '/centros-custo': typeof AppCentrosCustoRoute
  '/comparativo-composicao': typeof AppComparativoComposicaoRoute
  '/compliance': typeof AppComplianceRoute
  '/composicoes': typeof AppComposicoesRoute
  '/contratos': typeof AppContratosRoute
  '/cronogramas': typeof AppCronogramasRoute
  '/dossies': typeof AppDossiesRoute
  '/editais': typeof AppEditaisRoute
  '/equipamentos': typeof AppEquipamentosRoute
  '/equipe': typeof AppEquipeRoute
  '/estoque': typeof AppEstoqueRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/indices': typeof AppIndicesRoute
  '/insumos': typeof AppInsumosRouteWithChildren
  '/mao-de-obra': typeof AppMaoDeObraRoute
  '/medicoes': typeof AppMedicoesRoute
  '/notas-fiscais': typeof AppNotasFiscaisRoute
  '/obras': typeof AppObrasRoute
  '/oportunidades': typeof AppOportunidadesRoute
  '/parametros-financeiros': typeof AppParametrosFinanceirosRoute
  '/poderes': typeof AppPoderesRoute
  '/portais': typeof AppPortaisRoute
  '/propostas': typeof AppPropostasRouteWithChildren
  '/rdo': typeof AppRdoRoute
  '/reajustes': typeof AppReajustesRoute
  '/realizado': typeof AppRealizadoRoute
  '/invite/$token': typeof InviteTokenRoute
  '/': typeof AppIndexRoute
  '/assinaturas/relatorio': typeof AppAssinaturasRelatorioRoute
  '/configuracoes/zapsign': typeof AppConfiguracoesZapsignRouteWithChildren
  '/insumos/importar': typeof AppInsumosImportarRoute
  '/propostas/$id': typeof AppPropostasIdRoute
  '/api/public/zapsign-reminders': typeof ApiPublicZapsignRemindersRoute
  '/api/public/zapsign-webhook': typeof ApiPublicZapsignWebhookRoute
  '/configuracoes/zapsign/testes': typeof AppConfiguracoesZapsignTestesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/aditivos': typeof AppAditivosRoute
  '/_app/assinaturas': typeof AppAssinaturasRouteWithChildren
  '/_app/backup': typeof AppBackupRoute
  '/_app/biblioteca': typeof AppBibliotecaRoute
  '/_app/centros-custo': typeof AppCentrosCustoRoute
  '/_app/comparativo-composicao': typeof AppComparativoComposicaoRoute
  '/_app/compliance': typeof AppComplianceRoute
  '/_app/composicoes': typeof AppComposicoesRoute
  '/_app/contratos': typeof AppContratosRoute
  '/_app/cronogramas': typeof AppCronogramasRoute
  '/_app/dossies': typeof AppDossiesRoute
  '/_app/editais': typeof AppEditaisRoute
  '/_app/equipamentos': typeof AppEquipamentosRoute
  '/_app/equipe': typeof AppEquipeRoute
  '/_app/estoque': typeof AppEstoqueRoute
  '/_app/financeiro': typeof AppFinanceiroRoute
  '/_app/indices': typeof AppIndicesRoute
  '/_app/insumos': typeof AppInsumosRouteWithChildren
  '/_app/mao-de-obra': typeof AppMaoDeObraRoute
  '/_app/medicoes': typeof AppMedicoesRoute
  '/_app/notas-fiscais': typeof AppNotasFiscaisRoute
  '/_app/obras': typeof AppObrasRoute
  '/_app/oportunidades': typeof AppOportunidadesRoute
  '/_app/parametros-financeiros': typeof AppParametrosFinanceirosRoute
  '/_app/poderes': typeof AppPoderesRoute
  '/_app/portais': typeof AppPortaisRoute
  '/_app/propostas': typeof AppPropostasRouteWithChildren
  '/_app/rdo': typeof AppRdoRoute
  '/_app/reajustes': typeof AppReajustesRoute
  '/_app/realizado': typeof AppRealizadoRoute
  '/invite/$token': typeof InviteTokenRoute
  '/_app/': typeof AppIndexRoute
  '/_app/assinaturas/relatorio': typeof AppAssinaturasRelatorioRoute
  '/_app/configuracoes/zapsign': typeof AppConfiguracoesZapsignRouteWithChildren
  '/_app/insumos/importar': typeof AppInsumosImportarRoute
  '/_app/propostas/$id': typeof AppPropostasIdRoute
  '/api/public/zapsign-reminders': typeof ApiPublicZapsignRemindersRoute
  '/api/public/zapsign-webhook': typeof ApiPublicZapsignWebhookRoute
  '/_app/configuracoes/zapsign/testes': typeof AppConfiguracoesZapsignTestesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/aditivos'
    | '/assinaturas'
    | '/backup'
    | '/biblioteca'
    | '/centros-custo'
    | '/comparativo-composicao'
    | '/compliance'
    | '/composicoes'
    | '/contratos'
    | '/cronogramas'
    | '/dossies'
    | '/editais'
    | '/equipamentos'
    | '/equipe'
    | '/estoque'
    | '/financeiro'
    | '/indices'
    | '/insumos'
    | '/mao-de-obra'
    | '/medicoes'
    | '/notas-fiscais'
    | '/obras'
    | '/oportunidades'
    | '/parametros-financeiros'
    | '/poderes'
    | '/portais'
    | '/propostas'
    | '/rdo'
    | '/reajustes'
    | '/realizado'
    | '/invite/$token'
    | '/assinaturas/relatorio'
    | '/configuracoes/zapsign'
    | '/insumos/importar'
    | '/propostas/$id'
    | '/api/public/zapsign-reminders'
    | '/api/public/zapsign-webhook'
    | '/configuracoes/zapsign/testes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/reset-password'
    | '/aditivos'
    | '/assinaturas'
    | '/backup'
    | '/biblioteca'
    | '/centros-custo'
    | '/comparativo-composicao'
    | '/compliance'
    | '/composicoes'
    | '/contratos'
    | '/cronogramas'
    | '/dossies'
    | '/editais'
    | '/equipamentos'
    | '/equipe'
    | '/estoque'
    | '/financeiro'
    | '/indices'
    | '/insumos'
    | '/mao-de-obra'
    | '/medicoes'
    | '/notas-fiscais'
    | '/obras'
    | '/oportunidades'
    | '/parametros-financeiros'
    | '/poderes'
    | '/portais'
    | '/propostas'
    | '/rdo'
    | '/reajustes'
    | '/realizado'
    | '/invite/$token'
    | '/'
    | '/assinaturas/relatorio'
    | '/configuracoes/zapsign'
    | '/insumos/importar'
    | '/propostas/$id'
    | '/api/public/zapsign-reminders'
    | '/api/public/zapsign-webhook'
    | '/configuracoes/zapsign/testes'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/reset-password'
    | '/_app/aditivos'
    | '/_app/assinaturas'
    | '/_app/backup'
    | '/_app/biblioteca'
    | '/_app/centros-custo'
    | '/_app/comparativo-composicao'
    | '/_app/compliance'
    | '/_app/composicoes'
    | '/_app/contratos'
    | '/_app/cronogramas'
    | '/_app/dossies'
    | '/_app/editais'
    | '/_app/equipamentos'
    | '/_app/equipe'
    | '/_app/estoque'
    | '/_app/financeiro'
    | '/_app/indices'
    | '/_app/insumos'
    | '/_app/mao-de-obra'
    | '/_app/medicoes'
    | '/_app/notas-fiscais'
    | '/_app/obras'
    | '/_app/oportunidades'
    | '/_app/parametros-financeiros'
    | '/_app/poderes'
    | '/_app/portais'
    | '/_app/propostas'
    | '/_app/rdo'
    | '/_app/reajustes'
    | '/_app/realizado'
    | '/invite/$token'
    | '/_app/'
    | '/_app/assinaturas/relatorio'
    | '/_app/configuracoes/zapsign'
    | '/_app/insumos/importar'
    | '/_app/propostas/$id'
    | '/api/public/zapsign-reminders'
    | '/api/public/zapsign-webhook'
    | '/_app/configuracoes/zapsign/testes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ApiPublicZapsignRemindersRoute: typeof ApiPublicZapsignRemindersRoute
  ApiPublicZapsignWebhookRoute: typeof ApiPublicZapsignWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/realizado': {
      id: '/_app/realizado'
      path: '/realizado'
      fullPath: '/realizado'
      preLoaderRoute: typeof AppRealizadoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reajustes': {
      id: '/_app/reajustes'
      path: '/reajustes'
      fullPath: '/reajustes'
      preLoaderRoute: typeof AppReajustesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rdo': {
      id: '/_app/rdo'
      path: '/rdo'
      fullPath: '/rdo'
      preLoaderRoute: typeof AppRdoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/propostas': {
      id: '/_app/propostas'
      path: '/propostas'
      fullPath: '/propostas'
      preLoaderRoute: typeof AppPropostasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portais': {
      id: '/_app/portais'
      path: '/portais'
      fullPath: '/portais'
      preLoaderRoute: typeof AppPortaisRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/poderes': {
      id: '/_app/poderes'
      path: '/poderes'
      fullPath: '/poderes'
      preLoaderRoute: typeof AppPoderesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parametros-financeiros': {
      id: '/_app/parametros-financeiros'
      path: '/parametros-financeiros'
      fullPath: '/parametros-financeiros'
      preLoaderRoute: typeof AppParametrosFinanceirosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/oportunidades': {
      id: '/_app/oportunidades'
      path: '/oportunidades'
      fullPath: '/oportunidades'
      preLoaderRoute: typeof AppOportunidadesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/obras': {
      id: '/_app/obras'
      path: '/obras'
      fullPath: '/obras'
      preLoaderRoute: typeof AppObrasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notas-fiscais': {
      id: '/_app/notas-fiscais'
      path: '/notas-fiscais'
      fullPath: '/notas-fiscais'
      preLoaderRoute: typeof AppNotasFiscaisRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/medicoes': {
      id: '/_app/medicoes'
      path: '/medicoes'
      fullPath: '/medicoes'
      preLoaderRoute: typeof AppMedicoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mao-de-obra': {
      id: '/_app/mao-de-obra'
      path: '/mao-de-obra'
      fullPath: '/mao-de-obra'
      preLoaderRoute: typeof AppMaoDeObraRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insumos': {
      id: '/_app/insumos'
      path: '/insumos'
      fullPath: '/insumos'
      preLoaderRoute: typeof AppInsumosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/indices': {
      id: '/_app/indices'
      path: '/indices'
      fullPath: '/indices'
      preLoaderRoute: typeof AppIndicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financeiro': {
      id: '/_app/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/estoque': {
      id: '/_app/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof AppEstoqueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/equipe': {
      id: '/_app/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AppEquipeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/equipamentos': {
      id: '/_app/equipamentos'
      path: '/equipamentos'
      fullPath: '/equipamentos'
      preLoaderRoute: typeof AppEquipamentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/editais': {
      id: '/_app/editais'
      path: '/editais'
      fullPath: '/editais'
      preLoaderRoute: typeof AppEditaisRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dossies': {
      id: '/_app/dossies'
      path: '/dossies'
      fullPath: '/dossies'
      preLoaderRoute: typeof AppDossiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cronogramas': {
      id: '/_app/cronogramas'
      path: '/cronogramas'
      fullPath: '/cronogramas'
      preLoaderRoute: typeof AppCronogramasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contratos': {
      id: '/_app/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof AppContratosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/composicoes': {
      id: '/_app/composicoes'
      path: '/composicoes'
      fullPath: '/composicoes'
      preLoaderRoute: typeof AppComposicoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/compliance': {
      id: '/_app/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof AppComplianceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/comparativo-composicao': {
      id: '/_app/comparativo-composicao'
      path: '/comparativo-composicao'
      fullPath: '/comparativo-composicao'
      preLoaderRoute: typeof AppComparativoComposicaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/centros-custo': {
      id: '/_app/centros-custo'
      path: '/centros-custo'
      fullPath: '/centros-custo'
      preLoaderRoute: typeof AppCentrosCustoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/biblioteca': {
      id: '/_app/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof AppBibliotecaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/backup': {
      id: '/_app/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof AppBackupRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assinaturas': {
      id: '/_app/assinaturas'
      path: '/assinaturas'
      fullPath: '/assinaturas'
      preLoaderRoute: typeof AppAssinaturasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/aditivos': {
      id: '/_app/aditivos'
      path: '/aditivos'
      fullPath: '/aditivos'
      preLoaderRoute: typeof AppAditivosRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/zapsign-webhook': {
      id: '/api/public/zapsign-webhook'
      path: '/api/public/zapsign-webhook'
      fullPath: '/api/public/zapsign-webhook'
      preLoaderRoute: typeof ApiPublicZapsignWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/zapsign-reminders': {
      id: '/api/public/zapsign-reminders'
      path: '/api/public/zapsign-reminders'
      fullPath: '/api/public/zapsign-reminders'
      preLoaderRoute: typeof ApiPublicZapsignRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/propostas/$id': {
      id: '/_app/propostas/$id'
      path: '/$id'
      fullPath: '/propostas/$id'
      preLoaderRoute: typeof AppPropostasIdRouteImport
      parentRoute: typeof AppPropostasRoute
    }
    '/_app/insumos/importar': {
      id: '/_app/insumos/importar'
      path: '/importar'
      fullPath: '/insumos/importar'
      preLoaderRoute: typeof AppInsumosImportarRouteImport
      parentRoute: typeof AppInsumosRoute
    }
    '/_app/configuracoes/zapsign': {
      id: '/_app/configuracoes/zapsign'
      path: '/configuracoes/zapsign'
      fullPath: '/configuracoes/zapsign'
      preLoaderRoute: typeof AppConfiguracoesZapsignRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assinaturas/relatorio': {
      id: '/_app/assinaturas/relatorio'
      path: '/relatorio'
      fullPath: '/assinaturas/relatorio'
      preLoaderRoute: typeof AppAssinaturasRelatorioRouteImport
      parentRoute: typeof AppAssinaturasRoute
    }
    '/_app/configuracoes/zapsign/testes': {
      id: '/_app/configuracoes/zapsign/testes'
      path: '/testes'
      fullPath: '/configuracoes/zapsign/testes'
      preLoaderRoute: typeof AppConfiguracoesZapsignTestesRouteImport
      parentRoute: typeof AppConfiguracoesZapsignRoute
    }
  }
}

interface AppAssinaturasRouteChildren {
  AppAssinaturasRelatorioRoute: typeof AppAssinaturasRelatorioRoute
}

const AppAssinaturasRouteChildren: AppAssinaturasRouteChildren = {
  AppAssinaturasRelatorioRoute: AppAssinaturasRelatorioRoute,
}

const AppAssinaturasRouteWithChildren = AppAssinaturasRoute._addFileChildren(
  AppAssinaturasRouteChildren,
)

interface AppInsumosRouteChildren {
  AppInsumosImportarRoute: typeof AppInsumosImportarRoute
}

const AppInsumosRouteChildren: AppInsumosRouteChildren = {
  AppInsumosImportarRoute: AppInsumosImportarRoute,
}

const AppInsumosRouteWithChildren = AppInsumosRoute._addFileChildren(
  AppInsumosRouteChildren,
)

interface AppPropostasRouteChildren {
  AppPropostasIdRoute: typeof AppPropostasIdRoute
}

const AppPropostasRouteChildren: AppPropostasRouteChildren = {
  AppPropostasIdRoute: AppPropostasIdRoute,
}

const AppPropostasRouteWithChildren = AppPropostasRoute._addFileChildren(
  AppPropostasRouteChildren,
)

interface AppConfiguracoesZapsignRouteChildren {
  AppConfiguracoesZapsignTestesRoute: typeof AppConfiguracoesZapsignTestesRoute
}

const AppConfiguracoesZapsignRouteChildren: AppConfiguracoesZapsignRouteChildren =
  {
    AppConfiguracoesZapsignTestesRoute: AppConfiguracoesZapsignTestesRoute,
  }

const AppConfiguracoesZapsignRouteWithChildren =
  AppConfiguracoesZapsignRoute._addFileChildren(
    AppConfiguracoesZapsignRouteChildren,
  )

interface AppRouteChildren {
  AppAditivosRoute: typeof AppAditivosRoute
  AppAssinaturasRoute: typeof AppAssinaturasRouteWithChildren
  AppBackupRoute: typeof AppBackupRoute
  AppBibliotecaRoute: typeof AppBibliotecaRoute
  AppCentrosCustoRoute: typeof AppCentrosCustoRoute
  AppComparativoComposicaoRoute: typeof AppComparativoComposicaoRoute
  AppComplianceRoute: typeof AppComplianceRoute
  AppComposicoesRoute: typeof AppComposicoesRoute
  AppContratosRoute: typeof AppContratosRoute
  AppCronogramasRoute: typeof AppCronogramasRoute
  AppDossiesRoute: typeof AppDossiesRoute
  AppEditaisRoute: typeof AppEditaisRoute
  AppEquipamentosRoute: typeof AppEquipamentosRoute
  AppEquipeRoute: typeof AppEquipeRoute
  AppEstoqueRoute: typeof AppEstoqueRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppIndicesRoute: typeof AppIndicesRoute
  AppInsumosRoute: typeof AppInsumosRouteWithChildren
  AppMaoDeObraRoute: typeof AppMaoDeObraRoute
  AppMedicoesRoute: typeof AppMedicoesRoute
  AppNotasFiscaisRoute: typeof AppNotasFiscaisRoute
  AppObrasRoute: typeof AppObrasRoute
  AppOportunidadesRoute: typeof AppOportunidadesRoute
  AppParametrosFinanceirosRoute: typeof AppParametrosFinanceirosRoute
  AppPoderesRoute: typeof AppPoderesRoute
  AppPortaisRoute: typeof AppPortaisRoute
  AppPropostasRoute: typeof AppPropostasRouteWithChildren
  AppRdoRoute: typeof AppRdoRoute
  AppReajustesRoute: typeof AppReajustesRoute
  AppRealizadoRoute: typeof AppRealizadoRoute
  AppIndexRoute: typeof AppIndexRoute
  AppConfiguracoesZapsignRoute: typeof AppConfiguracoesZapsignRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAditivosRoute: AppAditivosRoute,
  AppAssinaturasRoute: AppAssinaturasRouteWithChildren,
  AppBackupRoute: AppBackupRoute,
  AppBibliotecaRoute: AppBibliotecaRoute,
  AppCentrosCustoRoute: AppCentrosCustoRoute,
  AppComparativoComposicaoRoute: AppComparativoComposicaoRoute,
  AppComplianceRoute: AppComplianceRoute,
  AppComposicoesRoute: AppComposicoesRoute,
  AppContratosRoute: AppContratosRoute,
  AppCronogramasRoute: AppCronogramasRoute,
  AppDossiesRoute: AppDossiesRoute,
  AppEditaisRoute: AppEditaisRoute,
  AppEquipamentosRoute: AppEquipamentosRoute,
  AppEquipeRoute: AppEquipeRoute,
  AppEstoqueRoute: AppEstoqueRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppIndicesRoute: AppIndicesRoute,
  AppInsumosRoute: AppInsumosRouteWithChildren,
  AppMaoDeObraRoute: AppMaoDeObraRoute,
  AppMedicoesRoute: AppMedicoesRoute,
  AppNotasFiscaisRoute: AppNotasFiscaisRoute,
  AppObrasRoute: AppObrasRoute,
  AppOportunidadesRoute: AppOportunidadesRoute,
  AppParametrosFinanceirosRoute: AppParametrosFinanceirosRoute,
  AppPoderesRoute: AppPoderesRoute,
  AppPortaisRoute: AppPortaisRoute,
  AppPropostasRoute: AppPropostasRouteWithChildren,
  AppRdoRoute: AppRdoRoute,
  AppReajustesRoute: AppReajustesRoute,
  AppRealizadoRoute: AppRealizadoRoute,
  AppIndexRoute: AppIndexRoute,
  AppConfiguracoesZapsignRoute: AppConfiguracoesZapsignRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  InviteTokenRoute: InviteTokenRoute,
  ApiPublicZapsignRemindersRoute: ApiPublicZapsignRemindersRoute,
  ApiPublicZapsignWebhookRoute: ApiPublicZapsignWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
