// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    let { data } = await supabase.auth.getSession()
    let token = data.session?.access_token
    const expiresAt = data.session?.expires_at ?? 0
    const nowSec = Math.floor(Date.now() / 1000)
    // Refresh if expired or about to expire in the next 30s.
    if (token && expiresAt && expiresAt - nowSec < 30) {
      const { data: refreshed } = await supabase.auth.refreshSession()
      token = refreshed.session?.access_token ?? token
    }
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
